name: dart-koii-lib

packages:
  - 'packages/**'

scripts:
  check_master:
    run: |
      melos run get \
      && melos run format \
      && melos run analyze \
      && melos run test --no-select \
      && melos run coverage --no-select

  get: melos exec -- dart pub get

  build: melos exec -- dart pub run build_runner build --delete-conflicting-outputs

  format: melos exec -- dart format --set-exit-if-changed -o none .

  analyze: melos exec -- dart analyze --fatal-infos .

  test: 
    run: melos exec -- dart run test --coverage=coverage
    select-package:
      dir-exists:
        - test

  coverage: 
    run: |
      melos exec --scope="koii" -- dart run coverage:format_coverage -i coverage -o coverage/coverage.lcov --lcov \
        --report-on=lib \
        --packages=.packages \
      && melos exec --scope="koii" -- "remove_from_coverage -f coverage/coverage.lcov -r '\.(g|freezed)\.dart$'"
    select-package:
      dir-exists:
        - test    
